language: ruby
script: "./.build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.2.0
env:
  global:
  - secure: ruvrQ1I66tqYPDjbShFZEe5SkCjXu13bSTR3RP52O/MQ481N+KVIxuTv7GwEhyOcN3awRp3d3jHcbXZPZJBOGkyJxaWPiS1GEvyM5LHx8XJNT+/Uo4ViETLa4VeRXIGPmGnMJmOFtLYkelSIgak6Y0iuM2EwH2bfepqMNBfjM54=
